[tool.poetry]
name = "sunflower"
version = "0.1.0"
description = ""
authors = ["Arkelis <guillaume.fayard@pycolore.fr>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
python-dotenv = "^0.10.3"
beautifulsoup4 = "^4.8"
flask = "^1.1"
flask-dotenv = "^0.1.2"
flask-cors = "^3.0"
redis = "^3.3"
daemonize = "^2.5"
mutagen = "^1.43"

[tool.poetry.dev-dependencies]
rope = "^0.16.0"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
