name: Reload Sunflower Radio on production

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
  workflow_dispatch:

jobs:
  reload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server and reload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ secrets.SUNFLOWER_PATH }} && poetry run python scripts/reload-after-push-on-production.py
